[build]
  command = "npm run build"
  publish = "dist/frontend/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  inputs = { skip = true }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
